export type PlaceDetail = {
  slug: string;
  name: string;
  nameHi: string;
  tagline: string;
  taglineHi: string;
  image: string;
  intro: string;
  introHi: string;
  sections: { heading: string; headingHi: string; body: string; bodyHi: string }[];
  metaDescription: string;
};

export const placeDetails: Record<string, PlaceDetail> = {
  mathura: {
    slug: 'mathura', name: 'Mathura', nameHi: 'मथुरा',
    tagline: 'The Divine Birthplace of Lord Shri Krishna', taglineHi: 'भगवान श्रीकृष्ण की दिव्य जन्मभूमि',
    image: '/attached_assets/Temple/Srikrishna_Janmabhoomi.png',
    intro: 'Mathura is one of the seven sacred Moksha-puris of Sanatan Dharma and the eternal birthplace of Bhagwan Shri Krishna. Sitting on the western bank of the holy Yamuna, this ancient city has been a centre of devotion, learning and pilgrimage for more than five thousand years. Every gali, ghat and temple of Mathura carries the fragrance of Krishna leela — from the prison cell where Krishna was born to the ghats where Vasudev carried Him across the rising Yamuna.',
    introHi: 'मथुरा सनातन धर्म की सात मोक्षपुरियों में से एक है तथा भगवान श्रीकृष्ण की शाश्वत जन्मभूमि है। पवित्र यमुना के पश्चिमी तट पर बसी यह प्राचीन नगरी पाँच हजार वर्षों से अधिक समय से भक्ति, ज्ञान और तीर्थाटन का केंद्र रही है। मथुरा की प्रत्येक गली, घाट और मंदिर कृष्ण-लीला की सुगंध से भरा है — उस कारागार से लेकर, जहाँ कृष्ण का जन्म हुआ, उन घाटों तक जहाँ से वसुदेव ने उन्हें उफनती यमुना के पार पहुँचाया।',
    sections: [
      { heading: 'Shri Krishna Janmabhoomi', headingHi: 'श्री कृष्ण जन्मभूमि', body: 'The Janmabhoomi temple complex marks the exact spot where Shri Krishna appeared on this earth in the prison of Kansa. The garbha-griha preserved within the complex is one of the most powerful darshan sites in Bharat. Devotees experience an unusual silence here — as if time itself bows before the place of His avatar.', bodyHi: 'जन्मभूमि मंदिर परिसर ठीक उसी स्थान को चिह्नित करता है जहाँ कंस की कारागार में श्रीकृष्ण ने अवतार लिया था। परिसर में सुरक्षित गर्भगृह भारत के सबसे शक्तिशाली दर्शन-स्थलों में से एक है। यहाँ भक्तों को एक विलक्षण मौन अनुभव होता है — मानो समय स्वयं भगवान की अवतार-स्थली के समक्ष नतमस्तक हो।' },
      { heading: 'Dwarkadhish Temple', headingHi: 'द्वारकाधीश मंदिर', body: 'Built in 1814, Dwarkadhish is the principal temple of the city and the spiritual centre of Mathura\'s daily life. The Holi, Janmashtami and Hindola utsav celebrations here are legendary, drawing lakhs of devotees in a sea of saffron and gulal.', bodyHi: 'सन् 1814 में निर्मित द्वारकाधीश मथुरा का प्रमुख मंदिर एवं नगर की दैनिक आध्यात्मिक चेतना का केंद्र है। यहाँ की होली, जन्माष्टमी और हिंडोला उत्सव विख्यात हैं, जिनमें केसरिया और गुलाल के सागर में लाखों भक्त उमड़ पड़ते हैं।' },
      { heading: 'Vishram Ghat & Yamuna Aarti', headingHi: 'विश्राम घाट और यमुना आरती', body: 'Vishram Ghat is the central ghat of Mathura where, according to tradition, Krishna rested after slaying Kansa. The evening Yamuna Aarti — with hundreds of diyas floating downstream — is one of the most moving spiritual experiences in all of Braj.', bodyHi: 'विश्राम घाट मथुरा का केंद्रीय घाट है जहाँ परंपरा के अनुसार कंस-वध के पश्चात् श्रीकृष्ण ने विश्राम किया था। संध्या-कालीन यमुना आरती — जब सैकड़ों दीप यमुना की धारा में बहते हैं — समस्त ब्रज की सबसे हृदय-स्पर्शी आध्यात्मिक अनुभूतियों में से एक है।' },
      { heading: 'Other Sacred Spots', headingHi: 'अन्य पवित्र स्थल', body: 'Potara Kund where Krishna\'s baby clothes were washed, Keshav Dev Temple, Gita Mandir, Birla Mandir and the 25-kosi Mathura parikrama are also essential parts of the yatra.', bodyHi: 'पोतरा कुंड (जहाँ बाल कृष्ण के वस्त्र धोए गए थे), केशव देव मंदिर, गीता मंदिर, बिड़ला मंदिर तथा 25-कोसी मथुरा परिक्रमा भी यात्रा के अनिवार्य अंग हैं।' },
      { heading: 'Best Time to Visit', headingHi: 'दर्शन का श्रेष्ठ समय', body: 'October to March is the most pleasant season. Janmashtami (Aug–Sep), Holi (March) and Kartik Purnima (Nov) bring the city to its most divine and crowded best.', bodyHi: 'अक्तूबर से मार्च तक का समय दर्शन के लिए सर्वाधिक सुखद है। जन्माष्टमी (अगस्त–सितंबर), होली (मार्च) और कार्तिक पूर्णिमा (नवंबर) के अवसर पर नगरी अपनी सर्वोच्च दिव्यता और जनसमूह में दिखाई देती है।' },
      { heading: 'Yatra Tips by Asthawaani', headingHi: 'आस्थावाणी की यात्रा सलाह', body: 'Stay near Vishram Ghat for early-morning darshan. Combine Mathura with Vrindavan (14 km), Gokul (15 km) and Govardhan (22 km) for a complete Braj-yatra of 3–4 days. Always cover your head in the garbha-griha and avoid leather inside temple premises.', bodyHi: 'प्रातः दर्शन हेतु विश्राम घाट के निकट ठहरना उत्तम है। 3–4 दिवसीय पूर्ण ब्रज-यात्रा हेतु मथुरा को वृंदावन (14 कि.मी.), गोकुल (15 कि.मी.) तथा गोवर्धन (22 कि.मी.) के साथ जोड़ें। गर्भगृह में सिर ढककर प्रवेश करें तथा मंदिर परिसर में चमड़े की वस्तुओं का प्रयोग न करें।' },
    ],
    metaDescription: 'Mathura — the divine birthplace of Lord Shri Krishna. Janmabhoomi, Dwarkadhish, Vishram Ghat and complete yatra guide on Asthawaani.',
  },
  vrindavan: {
    slug: 'vrindavan', name: 'Vrindavan', nameHi: 'वृंदावन',
    tagline: 'The Eternal Land of Divine Love and Bhakti', taglineHi: 'दिव्य प्रेम और भक्ति की शाश्वत भूमि',
    image: '/attached_assets/Temple/Prem_mandir.png',
    intro: 'Vrindavan is the eternal playground of Shri Radha and Shri Krishna. Set along the sacred Yamuna and surrounded by 12 forests of Braj, it is the land where the Lord\'s raas-leela, makhan-chori and divine flute still echo in every grove. For Vaishnavas, Vrindavan is not merely a place — it is the highest spiritual destination, a vibration of pure prem-bhakti where saints from Chaitanya Mahaprabhu to Hari Das Goswami immersed themselves in the names of Radha-Krishna.',
    introHi: 'वृंदावन श्री राधा और श्री कृष्ण की शाश्वत लीलाभूमि है। पवित्र यमुना के तट पर बसा और ब्रज के बारह वनों से घिरा यह वही स्थान है जहाँ आज भी प्रत्येक कुंज में भगवान की रास-लीला, माखन-चोरी और दिव्य वंशी-स्वर गूँजते हैं। वैष्णवों के लिए वृंदावन मात्र एक स्थान नहीं — यह सर्वोच्च आध्यात्मिक गंतव्य है, शुद्ध प्रेम-भक्ति का स्पंदन है, जहाँ चैतन्य महाप्रभु से लेकर हरिदास गोस्वामी तक संत राधा-कृष्ण के नामों में लीन हुए।',
    sections: [
      { heading: 'Banke Bihari Temple', headingHi: 'बांके बिहारी मंदिर', body: 'The most beloved temple of Vrindavan, where the deity of Banke Bihari Ji manifested to Swami Haridas in Nidhivan. The darshan is given in brief glimpses — a curtain is drawn every few seconds — because devotees cannot bear the unbroken power of His tribhanga form.', bodyHi: 'वृंदावन का सर्वप्रिय मंदिर, जहाँ निधिवन में स्वामी हरिदास जी के समक्ष बांके बिहारी जी प्रकट हुए थे। दर्शन क्षणिक झलकों में दिए जाते हैं — हर कुछ क्षण में पट गिरा दिए जाते हैं — क्योंकि भक्त उनके त्रिभंग स्वरूप की अखंड शक्ति को सह नहीं पाते।' },
      { heading: 'Prem Mandir', headingHi: 'प्रेम मंदिर', body: 'A breathtaking marble temple built by Jagadguru Shri Kripaluji Maharaj. Its evening light-and-fountain show, depicting Krishna leela, leaves every visitor in tears of devotion.', bodyHi: 'जगद्गुरु श्री कृपालु जी महाराज द्वारा निर्मित संगमरमर का अद्भुत मंदिर। यहाँ का संध्या-कालीन प्रकाश एवं फव्वारा शो, जो कृष्ण-लीला का चित्रण करता है, प्रत्येक दर्शनार्थी की आँखों में भक्ति के अश्रु ले आता है।' },
      { heading: 'ISKCON Krishna Balaram Mandir', headingHi: 'इस्कॉन कृष्ण-बलराम मंदिर', body: 'Founded by Srila Prabhupada, this is the international centre of Krishna consciousness with continuous kirtan, deity bhog and the samadhi of Prabhupada himself.', bodyHi: 'श्रील प्रभुपाद द्वारा स्थापित यह मंदिर कृष्ण-चेतना का अंतर्राष्ट्रीय केंद्र है, जहाँ निरंतर कीर्तन, विग्रह-भोग और स्वयं प्रभुपाद की समाधि स्थित है।' },
      { heading: 'Nidhivan & Seva Kunj', headingHi: 'निधिवन एवं सेवा कुंज', body: 'The mystical grove where, devotees believe, Radha-Krishna still perform raas-leela every night. The grove is locked at sundown and no human, animal or bird is permitted to stay inside.', bodyHi: 'वह रहस्यमय कुंज जहाँ भक्तों की मान्यता है कि आज भी प्रत्येक रात्रि राधा-कृष्ण रास-लीला करते हैं। सूर्यास्त के पश्चात् कुंज पर ताला लगा दिया जाता है — न मनुष्य, न पशु, न पक्षी किसी को भीतर रहने की अनुमति नहीं है।' },
      { heading: 'Other Must-Visit Temples', headingHi: 'अन्य अवश्य-दर्शनीय मंदिर', body: 'Radha Raman, Radha Vallabh, Radha Damodar, Shahji Temple, Rangji Temple and the recently built 213-metre Vrindavan Chandrodaya Mandir are all integral to a complete darshan.', bodyHi: 'राधा रमण, राधा वल्लभ, राधा दामोदर, शाहजी मंदिर, रंगजी मंदिर तथा हाल ही में निर्मित 213-मीटर वृंदावन चंद्रोदय मंदिर — सम्पूर्ण दर्शन के लिए ये सभी अनिवार्य हैं।' },
      { heading: 'Spiritual Significance', headingHi: 'आध्यात्मिक महत्व', body: 'It is said that the very dust (raj) of Vrindavan is liberating. Saints have declared that one moment of pure remembrance in Vrindavan equals years of sadhana elsewhere. Even a single yatra deepens bhakti for lifetimes.', bodyHi: 'कहा जाता है कि वृंदावन की रज स्वयं मुक्ति प्रदान करने वाली है। संतों ने घोषित किया है कि वृंदावन में शुद्ध स्मरण का एक क्षण अन्यत्र वर्षों की साधना के समान है। एक भी यात्रा भक्ति को जन्म-जन्मांतर तक गहरा कर देती है।' },
      { heading: 'Festivals to Plan Your Visit Around', headingHi: 'योजना बनाने योग्य प्रमुख उत्सव', body: 'Janmashtami, Radhashtami, Holi, Jhulan Yatra (Aug), Govardhan Puja and Kartik Deep Daan — each turns the entire town into a living festival of bhakti.', bodyHi: 'जन्माष्टमी, राधाष्टमी, होली, झूलन यात्रा (अगस्त), गोवर्धन पूजा और कार्तिक दीप-दान — इनमें से प्रत्येक सम्पूर्ण नगर को भक्ति के जीवंत उत्सव में परिवर्तित कर देता है।' },
    ],
    metaDescription: 'Vrindavan — the eternal land of Radha-Krishna leela. Banke Bihari, Prem Mandir, ISKCON, Nidhivan and complete yatra guide on Asthawaani.',
  },
  gokul: {
    slug: 'gokul', name: 'Gokul', nameHi: 'गोकुल',
    tagline: 'The Sacred Childhood Abode of Shri Krishna', taglineHi: 'श्रीकृष्ण की पवित्र बाल-लीला भूमि',
    image: '/attached_assets/Temple/Raman_reti.png',
    intro: 'Gokul is the gentle village on the eastern bank of the Yamuna where infant Krishna was secretly brought by Vasudev on the stormy night of His birth. Here, in the loving lap of Yashoda Maiya and under the watchful eyes of Nanda Baba, the Lord performed His sweetest bal-leelas — makhan chori, damodar leela, Putana-vadh and the lifting of the Shakatasura cart. Gokul is the place where the Supreme Brahman willingly became a child so His devotees could love Him as their own.',
    introHi: 'गोकुल यमुना के पूर्वी तट पर बसा वह स्नेहमय ग्राम है, जहाँ अपने जन्म की भयानक तूफानी रात्रि में वसुदेव गुप्त रूप से बाल कृष्ण को लाए थे। यहीं यशोदा मैया की वत्सल गोद में तथा नंद बाबा की सजग दृष्टि के नीचे भगवान ने अपनी सबसे मधुर बाल-लीलाएँ कीं — माखन चोरी, दामोदर लीला, पूतना-वध तथा शकटासुर के गाड़ी का उद्धार। गोकुल वह स्थान है जहाँ साक्षात् परब्रह्म स्वेच्छा से शिशु बने, ताकि भक्त उन्हें अपना समझकर प्रेम कर सकें।',
    sections: [
      { heading: 'Raman Reti', headingHi: 'रमन रेती', body: 'The soft golden sand where Krishna and Balram played with their gopa-friends. Devotees roll in this rajat-coloured sand as an act of bhakti, believing it carries the touch of the Lord\'s tiny feet.', bodyHi: 'वह मुलायम सुनहरी रेत जहाँ कृष्ण और बलराम अपने ग्वाल-सखाओं के साथ खेले। भक्त इस रजत-वर्णी रेत में लोटकर भक्ति प्रकट करते हैं, यह मानकर कि इसमें आज भी प्रभु के नन्हे चरणों का स्पर्श है।' },
      { heading: 'Nand Bhavan', headingHi: 'नंद भवन', body: 'The traditional home of Nanda Baba and Yashoda Maiya, where the family deities of Krishna are still worshipped. The murtis of bal-Krishna, Balram, Nanda, Yashoda and Rohini together create one of the most heart-melting darshans in all of Braj.', bodyHi: 'नंद बाबा एवं यशोदा मैया का पारंपरिक निवास, जहाँ आज भी कृष्ण के कुल-देवताओं की पूजा होती है। बाल-कृष्ण, बलराम, नंद, यशोदा तथा रोहिणी की संयुक्त मूर्तियाँ समस्त ब्रज के सबसे हृदय-द्रावक दर्शनों में से एक रचती हैं।' },
      { heading: 'Yashoda Ghat & Brahmand Ghat', headingHi: 'यशोदा घाट एवं ब्रह्मांड घाट', body: 'Brahmand Ghat is the legendary spot where Yashoda saw the entire universe inside baby Krishna\'s mouth. Standing here, devotees feel a direct sense of the Lord\'s infinite vatsalya.', bodyHi: 'ब्रह्मांड घाट वह विख्यात स्थल है जहाँ यशोदा ने बाल कृष्ण के मुख में सम्पूर्ण ब्रह्मांड के दर्शन किए थे। यहाँ खड़े होकर भक्त भगवान के अनंत वात्सल्य की प्रत्यक्ष अनुभूति करते हैं।' },
      { heading: 'Chaurasi Khamba (Mahavan)', headingHi: 'चौरासी खंभा (महावन)', body: 'Just beside Gokul lies Mahavan with the 84 ancient pillars of Nanda\'s original palace. The thakurani-ghat, Damodar pillar (where Krishna was tied) and the Putana-vadh sthal are all here.', bodyHi: 'गोकुल के ठीक निकट महावन है जहाँ नंद के मूल भवन के 84 प्राचीन स्तंभ खड़े हैं। ठकुरानी-घाट, दामोदर स्तंभ (जहाँ कृष्ण बाँधे गए थे) तथा पूतना-वध स्थल — सभी यहीं हैं।' },
      { heading: 'How to Reach & When to Visit', headingHi: 'पहुँचने का मार्ग एवं श्रेष्ठ समय', body: 'Gokul is 15 km south-east of Mathura, easily reached by auto, taxi or the Asthawaani-arranged Braj-yatra bus. Janmashtami, Nand Mahotsav (the day after Janmashtami) and Annakut are the most ecstatic times to visit.', bodyHi: 'गोकुल मथुरा से 15 कि.मी. दक्षिण-पूर्व में स्थित है, जहाँ ऑटो, टैक्सी अथवा आस्थावाणी द्वारा संचालित ब्रज-यात्रा बस से सरलता से पहुँचा जा सकता है। जन्माष्टमी, नंद महोत्सव (जन्माष्टमी के अगले दिन) तथा अन्नकूट दर्शन हेतु सर्वाधिक भावपूर्ण अवसर हैं।' },
    ],
    metaDescription: 'Gokul — childhood village of Shri Krishna. Raman Reti, Nand Bhavan, Brahmand Ghat and bal-leela darshan guide on Asthawaani.',
  },
  govardhan: {
    slug: 'govardhan', name: 'Govardhan', nameHi: 'गोवर्धन',
    tagline: 'The Sacred Hill Lifted by Shri Krishna', taglineHi: 'श्रीकृष्ण द्वारा उठाया गया पवित्र पर्वत',
    image: '/attached_assets/Temple/Daan_Ghati.png',
    intro: 'Govardhan is the sacred hill that Shri Krishna lifted on the little finger of His left hand for seven days and nights to shelter the people of Braj from the wrath of Indra. By that single act, the Lord declared that Govardhan itself is non-different from Him — and so, for over five thousand years, devotees have worshipped the hill as Giriraj Maharaj. The 21-kilometre parikrama of Govardhan is one of the most powerful spiritual practices in all of Sanatan Dharma.',
    introHi: 'गोवर्धन वह पवित्र पर्वत है जिसे श्रीकृष्ण ने इंद्र के क्रोध से ब्रजवासियों की रक्षा हेतु अपनी बायीं हाथ की कनिष्ठा पर सात दिन-रात तक उठाए रखा। उस एक लीला से भगवान ने घोषित किया कि गोवर्धन स्वयं उनसे अभिन्न है — और इसीलिए पाँच हजार वर्षों से अधिक समय से भक्त इस पर्वत की गिरिराज महाराज के रूप में पूजा करते आ रहे हैं। गोवर्धन की 21 किलोमीटर की परिक्रमा समस्त सनातन धर्म की सबसे शक्तिशाली साधनाओं में से एक है।',
    sections: [
      { heading: 'Daan Ghati Temple', headingHi: 'दान घाटी मंदिर', body: 'The spot where Krishna playfully demanded "daan" (toll) from the gopis carrying milk and butter to Mathura. The temple here is the customary starting point of the parikrama.', bodyHi: 'वह स्थल जहाँ श्रीकृष्ण ने मथुरा को दूध-मक्खन ले जाती गोपियों से लीलापूर्वक "दान" माँगा था। यहाँ का मंदिर परंपरागत रूप से परिक्रमा का प्रारंभ-बिंदु है।' },
      { heading: 'Mukharvind & Manasi Ganga', headingHi: 'मुखारविंद एवं मानसी गंगा', body: 'Mukharvind is the "face" of Giriraj Ji, where the Govardhan-shila is worshipped as the Lord Himself. Manasi Ganga, the holy lake created by Krishna\'s sankalp, is the place to bathe before beginning parikrama.', bodyHi: 'मुखारविंद गिरिराज जी का "मुख" है, जहाँ गोवर्धन-शिला की भगवान के रूप में पूजा होती है। मानसी गंगा, श्रीकृष्ण के संकल्प से उत्पन्न पवित्र सरोवर, परिक्रमा से पूर्व स्नान का स्थान है।' },
      { heading: 'Radha Kund & Shyam Kund', headingHi: 'राधा कुंड एवं श्याम कुंड', body: 'The two most sacred kunds in all of Braj. It is said that a bath in Radha Kund on Ahoi Ashtami midnight grants the rarest of all blessings — pure Radha-bhakti.', bodyHi: 'समस्त ब्रज के दो सर्वाधिक पवित्र कुंड। मान्यता है कि अहोई अष्टमी की मध्यरात्रि को राधा कुंड में स्नान सबसे दुर्लभ वरदान प्रदान करता है — शुद्ध राधा-भक्ति।' },
      { heading: 'The Parikrama', headingHi: 'गोवर्धन परिक्रमा', body: 'Devotees walk the 21 km route barefoot, chanting "Govardhan Maharaj ki Jai". Many perform the rarest form — dandavat parikrama — by full prostration, taking weeks to complete a single round. Asthawaani offers guided overnight parikrama with rest stops at Punchhari, Jatipura and Anyor.', bodyHi: 'भक्त 21 कि.मी. का यह मार्ग नंगे पाँव "गोवर्धन महाराज की जय" का उद्घोष करते हुए पूर्ण करते हैं। अनेक भक्त सबसे दुर्लभ रूप — दंडवत परिक्रमा — द्वारा साष्टांग प्रणाम करते हुए एक परिक्रमा को पूरा करने में सप्ताहों लगा देते हैं। आस्थावाणी पुंछरी, जतीपुरा और अनयोर में विश्राम-स्थलों के साथ रात्रिकालीन निर्देशित परिक्रमा संचालित करती है।' },
      { heading: 'Govardhan Puja & Annakut', headingHi: 'गोवर्धन पूजा एवं अन्नकूट', body: 'The day after Diwali, every home and temple in Braj prepares Annakut — a "mountain" of 56 (chappan) bhog dishes — and offers it to Giriraj Ji in remembrance of His protection.', bodyHi: 'दीपावली के अगले दिन ब्रज के प्रत्येक घर एवं मंदिर में अन्नकूट तैयार किया जाता है — 56 (छप्पन) भोग के व्यंजनों का "पर्वत" — और गिरिराज जी के संरक्षण के स्मरण में उन्हें अर्पित किया जाता है।' },
      { heading: 'Important Yatra Tips', headingHi: 'महत्वपूर्ण यात्रा सलाह', body: 'Carry water, wear breathable cotton, do not pluck or carry any stone from the hill, and try to complete parikrama between Brahma-muhurta and noon for the best experience.', bodyHi: 'जल साथ रखें, हल्के सूती वस्त्र पहनें, पर्वत से कोई शिला तोड़कर अथवा ले जाने का प्रयास न करें, तथा श्रेष्ठ अनुभव हेतु परिक्रमा ब्रह्म-मुहूर्त से दोपहर के बीच पूर्ण करें।' },
    ],
    metaDescription: 'Govardhan parikrama, Daan Ghati, Radha Kund, Manasi Ganga and the sacred hill lifted by Shri Krishna — full pilgrimage guide on Asthawaani.',
  },
  mahavan: {
    slug: 'mahavan', name: 'Mahavan', nameHi: 'महावन',
    tagline: 'The Forest of Krishna\'s Bal-Leelas', taglineHi: 'श्रीकृष्ण की बाल-लीलाओं का वन',
    image: '/attached_assets/Temple/mahaban_Chaurasi.png',
    intro: 'Mahavan — literally "the great forest" — is the ancient settlement just beside Gokul where Krishna actually spent the first phase of His earthly leela before the family shifted to Vrindavan. Today, its quiet lanes hold some of the most authentic and emotionally powerful spots of bal-leela: Chaurasi Khamba, the Damodar pillar where He was tied with the rope of Yashoda\'s love, the Putana-vadh sthal and Trinavarta-vadh sthal.',
    introHi: 'महावन — अर्थात् "महान वन" — गोकुल के ठीक निकट स्थित वह प्राचीन बस्ती है जहाँ श्रीकृष्ण ने वास्तव में अपनी पार्थिव लीला का प्रथम चरण व्यतीत किया, इससे पूर्व कि उनका परिवार वृंदावन चला जाए। आज इसकी शांत गलियाँ बाल-लीला के सबसे प्रामाणिक एवं भाव-प्रबल स्थलों को सहेजे हुए हैं: चौरासी खंभा, दामोदर स्तंभ (जहाँ यशोदा के स्नेह-बंधन से वे बाँधे गए थे), पूतना-वध स्थल तथा तृणावर्त-वध स्थल।',
    sections: [
      { heading: 'Chaurasi Khamba', headingHi: 'चौरासी खंभा', body: 'A single hall held up by 84 ancient pillars believed to be from Nanda Maharaj\'s original palace. Each pillar is regarded as a living witness of Krishna\'s childhood and is decorated with bhakti-paint by devotees.', bodyHi: 'एक ही भवन जिसे 84 प्राचीन स्तंभ धारण किए हुए हैं, जो नंद महाराज के मूल राजभवन के माने जाते हैं। प्रत्येक स्तंभ श्रीकृष्ण की बाल्यावस्था के जीवंत साक्षी के रूप में पूजित है तथा भक्तों द्वारा भक्ति-रंगों से अलंकृत होता रहता है।' },
      { heading: 'Damodar Pillar (Ukhal-Bandhan Sthal)', headingHi: 'दामोदर स्तंभ (ऊखल-बंधन स्थल)', body: 'The very spot where Yashoda Maiya tied baby Krishna to the wooden ukhal (mortar) — only to discover that no rope could ever match her love. From this leela arose the eternal name "Damodar".', bodyHi: 'वही स्थान जहाँ यशोदा मैया ने बाल कृष्ण को काष्ठ-ऊखल से बाँधा — और पाया कि कोई भी रस्सी उनके स्नेह की तुलना कभी नहीं कर सकती। इसी लीला से शाश्वत नाम "दामोदर" प्रकट हुआ।' },
      { heading: 'Putana-Vadh & Trinavarta-Vadh Sthal', headingHi: 'पूतना-वध एवं तृणावर्त-वध स्थल', body: 'The two preserved spots where infant Krishna, while still being carried in His mother\'s arms, freed the world from the demoness Putana and the whirlwind-demon Trinavarta.', bodyHi: 'दो संरक्षित स्थल जहाँ बाल कृष्ण ने माँ की गोद में रहते हुए ही जगत् को पूतना तथा बवंडर-रूपी तृणावर्त के आतंक से मुक्त किया था।' },
      { heading: 'Yogmaya Temple', headingHi: 'योगमाया मंदिर', body: 'Devoted to the divine sister of Krishna who was exchanged in the prison of Kansa. Worshipping Yogmaya before Janmabhoomi darshan is a traditional Braj practice.', bodyHi: 'श्रीकृष्ण की उन दिव्य भगिनी को समर्पित मंदिर, जिनका कंस के कारागार में परिवर्तन हुआ था। जन्मभूमि दर्शन से पूर्व योगमाया की पूजा ब्रज की पारंपरिक विधि है।' },
      { heading: 'Visiting Tips', headingHi: 'यात्रा सलाह', body: 'Combine Mahavan with Gokul in the same morning. The lanes are narrow — small EVs and rickshaws are the easiest way to move. Janmashtami and Annakut are the most powerful times to visit.', bodyHi: 'महावन को गोकुल के साथ एक ही प्रातः में सम्मिलित करें। यहाँ की गलियाँ सँकरी हैं — छोटी ई-रिक्शा एवं रिक्शा आवागमन का सबसे सरल साधन है। जन्माष्टमी तथा अन्नकूट दर्शन हेतु सर्वाधिक शक्तिशाली अवसर हैं।' },
    ],
    metaDescription: 'Mahavan & Chaurasi Khamba — the 84 ancient pillars of Krishna\'s original childhood home, Damodar pillar and bal-leela darshan on Asthawaani.',
  },
  barsana: {
    slug: 'barsana', name: 'Barsana', nameHi: 'बरसाना',
    tagline: 'The Divine Birthplace of Shri Radha Rani', taglineHi: 'श्री राधा रानी की दिव्य जन्मस्थली',
    image: '/attached_assets/Temple/Barsana_Radha_Rani.png',
    intro: 'Barsana is the lush hill-town that gave the world Shri Radha Rani — the very embodiment of prem-bhakti, the source of Krishna\'s own joy. Set on the four sacred hills of Brahma Parvat, Vishnu Parvat, Shankar Parvat and Brahma Giri, Barsana shines with the unparalleled energy of Radha\'s leelas. Here Radha grew up in the palace of Vrishabhanu Maharaj and Kirtida Maiya, and here the most ecstatic festival of Braj — Lathmar Holi — comes alive every year.',
    introHi: 'बरसाना वह हरा-भरा पर्वतीय नगर है जिसने जगत् को श्री राधा रानी प्रदान कीं — प्रेम-भक्ति की साक्षात् मूर्ति, श्रीकृष्ण के आनंद का मूल स्रोत। ब्रह्म पर्वत, विष्णु पर्वत, शंकर पर्वत तथा ब्रह्म गिरि — चार पवित्र पर्वतों पर बसा बरसाना राधा-लीलाओं की अद्वितीय ऊर्जा से चमकता है। यहाँ राधा वृषभानु महाराज और कीर्तिदा मैया के राजभवन में पली-बढ़ीं, और यहीं ब्रज का सबसे उत्सवपूर्ण पर्व — लठमार होली — प्रतिवर्ष जीवंत हो उठता है।',
    sections: [
      { heading: 'Shriji Temple (Radha Rani Mandir)', headingHi: 'श्रीजी मंदिर (राधा रानी मंदिर)', body: 'The principal temple of Radha Rani, standing atop Brahma Parvat. Devotees climb the 200+ steps chanting "Radhe Radhe", and at the top, witness the divine darshan of Ladli Lal Ji and Kishori Ji.', bodyHi: 'राधा रानी का मुख्य मंदिर, जो ब्रह्म पर्वत पर शोभायमान है। भक्त "राधे राधे" का उद्घोष करते हुए 200+ सीढ़ियाँ चढ़ते हैं और शिखर पर लाडली लाल जी एवं किशोरी जी के दिव्य दर्शन प्राप्त करते हैं।' },
      { heading: 'Mor Kutir & Maan Mandir', headingHi: 'मोर कुटीर एवं मान मंदिर', body: 'Mor Kutir is the sacred spot where Krishna once danced like a peacock to please an upset Radha. Maan Mandir is where Radha sat in divine "maan" (loving sulk) — and Krishna performed countless sweet acts to win Her back.', bodyHi: 'मोर कुटीर वह पवित्र स्थल है जहाँ श्रीकृष्ण ने रूठी राधा को मनाने हेतु मयूर के समान नृत्य किया था। मान मंदिर वह स्थान है जहाँ राधा दिव्य "मान" में बैठीं — और श्रीकृष्ण ने उन्हें मनाने हेतु असंख्य मधुर लीलाएँ कीं।' },
      { heading: 'Sankari Khor', headingHi: 'संकरी खोर', body: 'A narrow passage between Brahma Parvat and Vishnu Parvat where, according to leela, Krishna and His friends would tease Radha and the gopis on their way to Nandgaon. Even today, devotees re-enact the playful scene here.', bodyHi: 'ब्रह्म पर्वत एवं विष्णु पर्वत के बीच की सँकरी खोर, जहाँ लीला के अनुसार श्रीकृष्ण और उनके सखा नंदगाँव के मार्ग में राधा तथा गोपियों से ठिठोली किया करते थे। आज भी भक्त यहाँ उस मनोहर लीला का अभिनय करते हैं।' },
      { heading: 'Lathmar Holi', headingHi: 'लठमार होली', body: 'Eight days before Holi, the men of Nandgaon arrive in Barsana to play Holi — and the women of Barsana lovingly chase them away with long bamboo sticks. This unique, world-famous festival is the highest expression of the playful prem of Radha-Krishna.', bodyHi: 'होली से आठ दिन पूर्व नंदगाँव के पुरुष होली खेलने बरसाना आते हैं — और बरसाने की महिलाएँ उन्हें लम्बी बाँस की लाठियों से प्रेमपूर्वक खदेड़ती हैं। यह अद्वितीय, विश्व-विख्यात उत्सव राधा-कृष्ण के मनोहर प्रेम की सर्वोच्च अभिव्यक्ति है।' },
      { heading: 'Best Time & Yatra Combine', headingHi: 'श्रेष्ठ समय एवं यात्रा संयोजन', body: 'Radhashtami (Aug–Sep) and Lathmar Holi (Feb–March) are the most divine times. Combine Barsana with Nandgaon (8 km — the village of Nanda Baba) and Govardhan (21 km) in a single full-day yatra.', bodyHi: 'राधाष्टमी (अगस्त–सितंबर) तथा लठमार होली (फरवरी–मार्च) सर्वाधिक दिव्य अवसर हैं। बरसाना को नंदगाँव (8 कि.मी. — नंद बाबा का ग्राम) तथा गोवर्धन (21 कि.मी.) के साथ एक दिवसीय पूर्ण यात्रा में जोड़ें।' },
    ],
    metaDescription: 'Barsana — divine birthplace of Shri Radha Rani. Shriji Temple, Maan Mandir, Sankari Khor, Lathmar Holi and complete yatra guide on Asthawaani.',
  },
};

export const placeSlugs = Object.keys(placeDetails);
